import streamlit as st
import numpy as np
import pandas as pd
import joblib

# ============================================================
# CONFIGURATION
# ============================================================

MODEL_PATH = "hallucination_firewall_svm.pkl"

THRESHOLD = 0.30

FEATURE_COLUMNS = [
    "image_question_similarity",
    "image_answer_similarity",
    "multimodal_grounding_score"
]

# ============================================================
# PAGE CONFIG
# ============================================================

st.set_page_config(
    page_title="Multimodal Hallucination Firewall",
    page_icon="🛡️",
    layout="wide"
)

# ============================================================
# LOAD MODEL
# ============================================================

@st.cache_resource
def load_model():
    return joblib.load(MODEL_PATH)

try:
    model = load_model()
except Exception as e:
    st.error("Unable to load the trained firewall model.")
    st.code(str(e))
    st.stop()

# ============================================================
# HEADER
# ============================================================

st.title("🛡️ Multimodal Hallucination Firewall")

st.markdown(
    """
    ### Detect whether an AI-generated answer is supported by
    multimodal evidence.

    The trained SVM firewall uses three CLIP-derived features:
    """
)

# ============================================================
# INPUT
# ============================================================

col1, col2 = st.columns(2)

with col1:

    st.subheader("📷 Image")

    uploaded_image = st.file_uploader(
        "Upload an image",
        type=["jpg", "jpeg", "png"]
    )

    if uploaded_image is not None:

        st.image(
            uploaded_image,
            caption="Uploaded Image",
            use_container_width=True
        )

with col2:

    st.subheader("💬 Question & Answer")

    question = st.text_input(
        "Question",
        placeholder="Enter the question asked about the image"
    )

    answer = st.text_area(
        "AI-generated answer",
        placeholder="Enter the answer generated by the AI model"
    )

# ============================================================
# FEATURE VALUES
# ============================================================

st.divider()

st.subheader("🔬 CLIP-Derived Evidence Features")

st.info(
    """
    Enter the feature values produced by the project's CLIP
    feature-extraction pipeline.
    """
)

c1, c2, c3 = st.columns(3)

with c1:
    image_question_similarity = st.number_input(
        "Image–Question Similarity",
        min_value=0.0,
        max_value=1.0,
        value=0.2800,
        step=0.0001
    )

with c2:
    image_answer_similarity = st.number_input(
        "Image–Answer Similarity",
        min_value=0.0,
        max_value=1.0,
        value=0.2783,
        step=0.0001
    )

with c3:
    grounding_score = st.number_input(
        "Multimodal Grounding Score",
        min_value=0.0,
        max_value=1.0,
        value=0.2792,
        step=0.0001
    )

# ============================================================
# FIREWALL
# ============================================================

if st.button(
    "🔍 CHECK ANSWER",
    type="primary",
    use_container_width=True
):

    if uploaded_image is None:
        st.warning("Please upload an image.")

    elif not question.strip():
        st.warning("Please enter a question.")

    elif not answer.strip():
        st.warning("Please enter the AI-generated answer.")

    else:

        # ----------------------------------------------------
        # CREATE MODEL INPUT
        # ----------------------------------------------------

        X = pd.DataFrame(
            [[
                image_question_similarity,
                image_answer_similarity,
                grounding_score
            ]],
            columns=FEATURE_COLUMNS
        )

        # ----------------------------------------------------
        # PREDICTION
        # ----------------------------------------------------

        prediction = model.predict(X)[0]

        if hasattr(model, "predict_proba"):
            score = model.predict_proba(X)[0, 1]

        else:
            score = float(prediction)

        # ----------------------------------------------------
        # DECISION
        # ----------------------------------------------------

        if score >= THRESHOLD:

            decision = "HALLUCINATED"

            st.error(
                "🚨 HALLUCINATED\n\n"
                "The firewall has flagged this answer as "
                "potentially unsupported by the visual evidence."
            )

        else:

            decision = "SUPPORTED"

            st.success(
                "✅ SUPPORTED\n\n"
                "The firewall considers this answer supported."
            )

        # ----------------------------------------------------
        # RESULTS
        # ----------------------------------------------------

        st.divider()

        r1, r2 = st.columns(2)

        with r1:
            st.metric(
                "Firewall Score",
                f"{score:.4f}"
            )

        with r2:
            st.metric(
                "Decision",
                decision
            )

        # ----------------------------------------------------
        # FEATURE BREAKDOWN
        # ----------------------------------------------------

        st.subheader("📊 Evidence Breakdown")

        result_df = pd.DataFrame({
            "Feature": [
                "Image–Question Similarity",
                "Image–Answer Similarity",
                "Multimodal Grounding Score"
            ],
            "Value": [
                image_question_similarity,
                image_answer_similarity,
                grounding_score
            ]
        })

        st.dataframe(
            result_df,
            use_container_width=True,
            hide_index=True
        )

        st.caption(
            f"Decision threshold: {THRESHOLD:.2f}"
        )

# ============================================================
# FOOTER
# ============================================================

st.divider()

st.caption(
    "Multimodal Hallucination Firewall | "
    "CLIP + SVM | MSc AI & ML Project"
)
